export const CREATE_COMMANDE_REQUEST = 'CREATE_COMMANDE_REQUEST'
export const CREATE_COMMANDE_FAIL = 'CREATE_COMMANDE_FAIL'
export const CREATE_COMMANDE_SUCCESS = 'CREATE_COMMANDE_SUCCESS'

export const GET_ALL_COMMANDE_BY_USER = "GET_ALL_COMMANDE_BY_USER"


export const GET_COMMAND_DETAILS_REQUEST = 'GET_COMMAND_DETAILS_REQUEST'
export const GET_COMMAND_DETAILS_FAIL = 'GET_COMMAND_DETAILS_FAIL'
export const GET_COMMAND_DETAILS_SUCCESS = 'GET_COMMAND_DETAILS_SUCCESS'