export const GET_PANIER_SUCCESS = 'GET_PANIER_SUCCESS'


export const ADD_PANIER_ITEM = 'ADD_PANIER_ITEM'


export const DELETE_PANIER_ITEM = 'DELETE_PANIER_ITEM'



export const VIDER_PANIER_REQUEST = 'VIDER_PANIER_REQUEST' 
 
