export const GET_PRODUCT_LOADING = 'GET_PRODUCT_LOADING'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL'



export const GET_TOPPRODUCT_SUCCESS = 'GET_TOPPRODUCT_SUCCESS'


export const GET_PRODUCT_ID_SUCCESS =  'GET_PRODUCT_ID_SUCCESS'
export const GET_PRODUCT_ID_REQUEST =  'GET_PRODUCT_ID_REQUEST'
export const GET_PRODUCT_ID_ERROR  =  'GET_PRODUCT_ID_ERROR '



 
export const GET_PRODUCT_BY_CATEGORIE_ERROR =  'GET_PRODUCT_BY_CATEGORIE_ERROR'
export const GET_PRODUCT_BY_CATEGORIE_REQUEST =  'GET_PRODUCT_BY_CATEGORIE_REQUEST'
export const GET_PRODUCT_BY_CATEGORIE_SUCCESS = 'GET_PRODUCT_BY_CATEGORIE_SUCCESS'