export const GET_USER_SIGIN_SUCCESS = 'GET_USER_SIGIN_SUCCESS'
export const GET_USER_SIGIN_FAIL = 'GET_USER_SIGIN_FAIL'
export const GET_USER_SIGIN_REQUEST = 'GET_USER_SIGIN_FAIL_REQUEST'

export const CREATE_USER_SUCESS = 'CREATE_USER_SUCESS'
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL'


export const UPDATE_USER_SUCESS = 'UPDATE_USER_SUCESS'

export const LOGOUT_REQUEST = ' LOGOUT_REQUEST'
export const LOGOUT_ERROR = ' LOGOUT_ERROR'
 
